### ISSUE TITLE
Clean up discord ghost processes when closing

### ISSUE THREAD

**Issue by titushm** [RJ-Infinity/ThisCord#18]
Discord sometimes leaves ghost processes open even when quit, we need to close these to avoid messing up stuff

**Comment by RJ-Infinity** [comment]
the first question here is "is this beacuse of ThisCord or is it a bug with discord?" beacuse if it is thiscord it should be fixed but if its discord we have two options.
1. create a workaround for the issue. i.e. notice when this bug is happening and kill all discord processes. there are however issues with this. i.e. it will slow down the standard opening of thiscord
2. or we could fix the issue. this however will mean that if you close a non injected instance then you will have the issue on the next startup (also does this issue effect standard discord starting or is it just when its done with ThisCord?)

**Comment by titushm** [comment]
They are seperate, this is for cleaning processes.
#2 is for getting a more stable injection

**Comment by titushm** [comment]
> the first question here is "is this beacuse of ThisCord or is it a bug with discord?" beacuse if it is thiscord it should be fixed but if its discord we have two options.
> 
> 1. create a workaround for the issue. i.e. notice when this bug is happening and kill all discord processes. there are however issues with this. i.e. it will slow down the standard opening of thiscord
> 2. or we could fix the issue. this however will mean that if you close a non injected instance then you will have the issue on the next startup (also does this issue effect standard discord starting or is it just when its done with ThisCord?)

Bug with discord needs to be fixed either way

**Comment by titushm** [comment]
I'm thinking maybe the backend
